package com.android.utils.cxx;

import com.sun.jna.platform.win32.WinError;
import kotlin.Metadata;

/* compiled from: CxxDiagnosticCode.kt */
@Metadata(d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0010\b\n\u0002\b8\b\u0086\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\u000f\b\u0002\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004R\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u0005\u0010\u0006R\u0011\u0010\u0007\u001a\u00020\u00038F¢\u0006\u0006\u001a\u0004\b\b\u0010\u0006j\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:¨\u0006;"}, d2 = {"Lcom/android/utils/cxx/CxxDiagnosticCode;", "", "errorCode", "", "(Ljava/lang/String;II)V", "getErrorCode", "()I", "warningCode", "getWarningCode", "GENERIC", "NDK_IS_AMBIGUOUS", "NDK_CORRUPTED", "NDK_IS_INVALID", "NDK_VERSION_IS_INVALID", "NDK_VERSION_IS_UNMATCHED", "NDK_VERSION_UNSUPPORTED", "NDK_DIR_IS_DEPRECATED", "NDK_FEATURE_NOT_SUPPORTED_FOR_VERSION", "ABI_IS_INVALID", "ABI_IS_UNSUPPORTED", "ABI_HAS_ONLY_32_BIT_SUPPORT", "PREFAB_NO_LIBRARY_FOUND", "PREFAB_SINGLE_STL_VIOLATION_LIBRARY_IS_SHARED_WITH_STATIC_STL", "PREFAB_SINGLE_STL_VIOLATION_LIBRARY_REQUIRES_SHARED_STL", "PREFAB_MISMATCHED_STL_TYPE", "PREFAB_MISMATCHED_MIN_SDK_VERSION", "PREFAB_DUPLICATE_MODULE_NAME", "PREFAB_UNSUPPORTED_PLATFORM", "PREFAB_MISMATCHED_SCHEMA", "PREFAB_JSON_FORMAT_PROBLEM", "PREFAB_PREBUILTS_MISSING", "PREFAB_FATAL", "CMAKE_IS_MISSING", "CMAKE_VERSION_IS_INVALID", "CMAKE_VERSION_IS_UNSUPPORTED", "CMAKE_FEATURE_NOT_SUPPORTED_FOR_VERSION", "CMAKE_PACKAGES_SDK", "CMAKE_SERVER_BUILD_DIRECTORY_MISSING", "INVALID_EXTERNAL_NATIVE_BUILD_CONFIG", "INVALID_COMPILER_SWITCH", "EXTRA_OUTPUT", "NO_STL_FOUND", "REQUIRED_BUILD_TARGETS_MISSING", "METADATA_GENERATION_FAILURE", "OBJECT_FILE_CANT_BE_CONVERTED_TO_TARGET_NAME", "COULD_NOT_EXTRACT_OUTPUT_FILE_FROM_CLANG_COMMAND", "COULD_NOT_CANONICALIZE_PATH", "BUILD_FILE_DID_NOT_EXIST", "BUILD_TARGET_COMMAND_COMPONENTS_DID_NOT_EXIST", "BUILD_TARGET_COMMAND_COMPONENTS_COMMAND_DID_NOT_EXIST", "LIBRARY_ARTIFACT_NAME_DID_NOT_EXIST", "LIBRARY_ABI_NAME_DID_NOT_EXIST", "LIBRARY_HAD_MULTIPLE_ABIS", "LIBRARY_ABI_NAME_IS_INVALID", "NINJA_IS_MISSING", "BUILD_NINJA_NOT_GENERATED", "NINJA_CONFIGURE_SCRIPT_MISSING", "NINJA_CONFIGURE_INVALID_ARGUMENTS", "BUILD_CACHE_DISABLED_ACCESS", "common"}, k = 1, mv = {1, 5, 1}, xi = 48)
/* loaded from: classes3.dex */
public enum CxxDiagnosticCode {
    GENERIC(1000),
    NDK_IS_AMBIGUOUS(WinError.ERROR_END_OF_MEDIA),
    NDK_CORRUPTED(WinError.ERROR_FILEMARK_DETECTED),
    NDK_IS_INVALID(WinError.ERROR_BEGINNING_OF_MEDIA),
    NDK_VERSION_IS_INVALID(WinError.ERROR_SETMARK_DETECTED),
    NDK_VERSION_IS_UNMATCHED(WinError.ERROR_NO_DATA_DETECTED),
    NDK_VERSION_UNSUPPORTED(WinError.ERROR_PARTITION_FAILURE),
    NDK_DIR_IS_DEPRECATED(WinError.ERROR_INVALID_BLOCK_LENGTH),
    NDK_FEATURE_NOT_SUPPORTED_FOR_VERSION(WinError.ERROR_DEVICE_NOT_PARTITIONED),
    ABI_IS_INVALID(1200),
    ABI_IS_UNSUPPORTED(WinError.ERROR_CONNECTION_UNAVAIL),
    ABI_HAS_ONLY_32_BIT_SUPPORT(WinError.ERROR_DEVICE_ALREADY_REMEMBERED),
    PREFAB_NO_LIBRARY_FOUND(WinError.ERROR_INVALID_COMPUTERNAME),
    PREFAB_SINGLE_STL_VIOLATION_LIBRARY_IS_SHARED_WITH_STATIC_STL(WinError.ERROR_INVALID_EVENTNAME),
    PREFAB_SINGLE_STL_VIOLATION_LIBRARY_REQUIRES_SHARED_STL(WinError.ERROR_INVALID_DOMAINNAME),
    PREFAB_MISMATCHED_STL_TYPE(WinError.ERROR_INVALID_SERVICENAME),
    PREFAB_MISMATCHED_MIN_SDK_VERSION(WinError.ERROR_INVALID_NETNAME),
    PREFAB_DUPLICATE_MODULE_NAME(WinError.ERROR_INVALID_SHARENAME),
    PREFAB_UNSUPPORTED_PLATFORM(WinError.ERROR_INVALID_PASSWORDNAME),
    PREFAB_MISMATCHED_SCHEMA(WinError.ERROR_INVALID_MESSAGENAME),
    PREFAB_JSON_FORMAT_PROBLEM(WinError.ERROR_INVALID_MESSAGEDEST),
    PREFAB_PREBUILTS_MISSING(WinError.ERROR_SESSION_CREDENTIAL_CONFLICT),
    PREFAB_FATAL(WinError.ERROR_REMOTE_SESSION_LIMIT_EXCEEDED),
    CMAKE_IS_MISSING(WinError.ERROR_NOT_ALL_ASSIGNED),
    CMAKE_VERSION_IS_INVALID(WinError.ERROR_SOME_NOT_MAPPED),
    CMAKE_VERSION_IS_UNSUPPORTED(WinError.ERROR_NO_QUOTAS_FOR_ACCOUNT),
    CMAKE_FEATURE_NOT_SUPPORTED_FOR_VERSION(WinError.ERROR_LOCAL_USER_SESSION_KEY),
    CMAKE_PACKAGES_SDK(WinError.ERROR_NULL_LM_PASSWORD),
    CMAKE_SERVER_BUILD_DIRECTORY_MISSING(WinError.ERROR_UNKNOWN_REVISION),
    INVALID_EXTERNAL_NATIVE_BUILD_CONFIG(WinError.ERROR_INVALID_WINDOW_HANDLE),
    INVALID_COMPILER_SWITCH(WinError.ERROR_INVALID_MENU_HANDLE),
    EXTRA_OUTPUT(WinError.ERROR_INVALID_CURSOR_HANDLE),
    NO_STL_FOUND(WinError.ERROR_INVALID_ACCEL_HANDLE),
    REQUIRED_BUILD_TARGETS_MISSING(WinError.ERROR_INVALID_HOOK_HANDLE),
    METADATA_GENERATION_FAILURE(WinError.ERROR_INVALID_DWP_HANDLE),
    OBJECT_FILE_CANT_BE_CONVERTED_TO_TARGET_NAME(WinError.ERROR_TLW_WITH_WSCHILD),
    COULD_NOT_EXTRACT_OUTPUT_FILE_FROM_CLANG_COMMAND(WinError.ERROR_CANNOT_FIND_WND_CLASS),
    COULD_NOT_CANONICALIZE_PATH(WinError.ERROR_WINDOW_OF_OTHER_THREAD),
    BUILD_FILE_DID_NOT_EXIST(WinError.ERROR_HOTKEY_ALREADY_REGISTERED),
    BUILD_TARGET_COMMAND_COMPONENTS_DID_NOT_EXIST(WinError.ERROR_CLASS_ALREADY_EXISTS),
    BUILD_TARGET_COMMAND_COMPONENTS_COMMAND_DID_NOT_EXIST(WinError.ERROR_CLASS_DOES_NOT_EXIST),
    LIBRARY_ARTIFACT_NAME_DID_NOT_EXIST(WinError.ERROR_CLASS_HAS_WINDOWS),
    LIBRARY_ABI_NAME_DID_NOT_EXIST(WinError.ERROR_INVALID_INDEX),
    LIBRARY_HAD_MULTIPLE_ABIS(WinError.ERROR_INVALID_ICON_HANDLE),
    LIBRARY_ABI_NAME_IS_INVALID(WinError.ERROR_PRIVATE_DIALOG_INDEX),
    NINJA_IS_MISSING(WinError.ERROR_LISTBOX_ID_NOT_FOUND),
    BUILD_NINJA_NOT_GENERATED(WinError.ERROR_NO_WILDCARD_CHARACTERS),
    NINJA_CONFIGURE_SCRIPT_MISSING(WinError.ERROR_CLIPBOARD_NOT_OPEN),
    NINJA_CONFIGURE_INVALID_ARGUMENTS(WinError.ERROR_HOTKEY_NOT_REGISTERED),
    BUILD_CACHE_DISABLED_ACCESS(1500);

    private final int errorCode;

    CxxDiagnosticCode(int i) {
        this.errorCode = i;
    }

    public final int getErrorCode() {
        return this.errorCode;
    }

    public final int getWarningCode() {
        return this.errorCode + 4000;
    }
}
